[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5KERD
    MinStakeValue = "100000000000000000000" #100ERD
    UnBondPeriod = 144000
    MinStepValue = "100000000000000000000"
    AuctionEnableNonce = 100000000000
    StakeEnableNonce = 100000000000
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 28
    NodesToSelectInAuction = 28
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = false

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5ERD
    OwnerAddress = "erd1ze6pgefwc7mdx0rhje3h50kkgt26ut3gx8ytezndkz8fjcf96gsqsd7ugw"
    Disabled = true

[GovernanceSystemSCConfig]
	ProposalCost = "5000000000000000000" #5ERD
	NumNodes     = 500
	MinQuorum    = 400
	MinPassThreshold = 300
	MinVetoThreshold = 50
	Disabled     = true
